services:
    front:
        build: .
        volumes:
            - front_data:/app/dist

    nginx:
        image: nginx:latest
        ports:
            - '80:80'
        depends_on:
            - front
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - front_data:/usr/share/nginx/html/
        restart: always

volumes:
    front_data: